name: rick_and_morty
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed: 2.4.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  google_fonts: any
  dio: ^5.2.1+1
  http: ^1.1.0
  retrofit: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8

flutter:
  uses-material-design: true
  assets:
    - assets/
